---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: cert-manager
  chart:
    git: git@github.com:nataz77/osmdemo-k8s.git
    path: charts/cert-manager
    ref: master
  values:    
    replicaCount: 1
    installCRDs: true