---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: nginx-ingress
  chart:
    git: git@github.com:nataz77/osmdemo-k8s.git
    path: charts/nginx
    ref: master
  values:
    image:
      repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
      tag: "dev"
    replicaCount: 3
